name: Cross-Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master-cmake'
      - '!**4.4'
  pull_request:
    branches:
      - 'master-cmake'
      - '!**4.4'

jobs:
  job1:
    name: Build Number
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate common build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      max-parallel: 1
      matrix:
        node: [I2S-4MFlash, SqueezeAmp, Muse]
        depth: [16, 32]
        exclude:
          - node: Muse
            depth: 32
    steps:
      - name: Set target name
        run: |
          echo "TARGET_BUILD_NAME=${{ matrix.node }}" >> $GITHUB_ENV
   
