name: Cross-Build (ESP32-S3)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32s3]
        flash: [16]
    env:
      IDF_PATH: /opt/esp/idf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: esp-idf-${{ matrix.target }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Set up ESP-IDF (v4.4)
        run: |
          git clone -b release/v4.4 --depth=1 https://github.com/espressif/esp-idf.git /opt/esp/idf
          /opt/esp/idf/install.sh

      - name: Export IDF
        run: source /opt/esp/idf/export.sh

      - name: Build Squeezelite for ESP32-S3
        run: |
          mkdir -p build
          idf.py set-target esp32s3
          idf.py build

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: squeezelite-esp32s3-${{ matrix.flash }}MB
          path: |
            build/*.bin
            build/*.elf
            build/*.map
